import { describe, expect, it } from 'vitest';
import { computeBacklog, BACKLOG_CAUGHT_UP_THRESHOLD } from '../backlog';
import { DEFAULTS } from '../types';
import type { Grid, ShiftDef } from '../types';

const DECAY = DEFAULTS.backlogHourlyDecay; // 0.85

// A single shift covering all 24h — lets us drive capacity purely via one headcount value.
const allDay: ShiftDef[] = [{ id: 'all', label: '24h', startHour: 0, lengthHours: 24 }];
// A 2-shift menu that tiles the day with no overlap: day 7a-7p, night 7p-7a.
const dayNight: ShiftDef[] = [
  { id: 'day', label: '7a-7p', startHour: 7, lengthHours: 12 },
  { id: 'night', label: '7p-7a', startHour: 19, lengthHours: 12 },
];

/** Grid where every day staffs `hc` on the given single shift → flat capacity. */
function flatGrid(shiftId: string, hc: number): Grid {
  const g: Grid = {};
  for (let day = 0; day < 7; day++) g[day] = { [shiftId]: hc };
  return g;
}

function zeros(): number[] {
  return new Array(168).fill(0);
}

describe('§2.4 backlog diagnostic', () => {
  it('is all zero when capacity always meets demand (no one falls behind)', () => {
    const res = computeBacklog({}, zeros(), allDay);
    expect(res.backlog.every((b) => b === 0)).toBe(true);
    expect(res.longestStreakHours).toBe(0);
    expect(res.longestStreakStart).toBeNull();
    expect(res.neverClears).toBe(false);
    expect(res.peakBacklog).toBe(0);
  });

  it('converges to the geometric steady state under a constant deficit', () => {
    // requirement 1 everywhere, capacity 0 → deficit 1 every hour.
    // Circular steady state: x = decay*x + 1  ⇒  x = 1/(1-decay).
    const req = new Array(168).fill(1);
    const res = computeBacklog({}, req, allDay);
    const steady = 1 / (1 - DECAY); // ≈ 6.667
    expect(res.backlog[100]).toBeCloseTo(steady, 6);
    expect(res.backlog[167]).toBeCloseTo(steady, 6);
    expect(res.neverClears).toBe(true); // 6.67 >= threshold everywhere
    expect(res.longestStreakHours).toBe(168);
    expect(res.typicalClearHour).toBeNull();
  });

  it('carries backlog across the Sat→Sun week boundary with NO reset (spec §2.4)', () => {
    // Deficit only in the very last hour of the week (day 6, hour 23 = global 167).
    const req = zeros();
    req[167] = 5;
    const res = computeBacklog({}, req, allDay);
    expect(res.backlog[167]).toBeCloseTo(5, 6);
    // The hole must bleed into Sunday hour 0 — this is the whole point of "no boundary reset".
    expect(res.backlog[0]).toBeCloseTo(5 * DECAY, 6); // 4.25
    expect(res.backlog[1]).toBeCloseTo(5 * DECAY * DECAY, 6);
    // The streak wraps 167 → 0 → 1 …; longestStreakStart should anchor at the wrap point.
    expect(res.longestStreakStart).toEqual({ day: 6, hour: 23 });
    // behind hours: g=167 plus g=0..13 where 5*0.85^(k+1) >= 0.5 ⇒ 15 consecutive.
    expect(res.longestStreakHours).toBe(15);
    expect(res.neverClears).toBe(false);
  });

  it('excess capacity actively pays backlog down faster than passive decay alone', () => {
    // Both scenarios share an identical deficit spike of 10 at global hour 0.
    // Scenario A: no excess capacity afterward (deficit 0) → pure 0.85/hr decay.
    const reqA = zeros();
    reqA[0] = 10;
    const a = computeBacklog({}, reqA, allDay);
    // Scenario B: capacity 2 everywhere; req 12 at hour 0 → same deficit 10, but -2/hr after.
    const reqB = zeros();
    reqB[0] = 12;
    const b = computeBacklog(flatGrid('all', 2), reqB, allDay);

    expect(a.backlog[0]).toBeCloseTo(10, 6);
    expect(b.backlog[0]).toBeCloseTo(10, 6);
    // By hour 3 the actively-paid-down backlog is well below the passively-decayed one.
    expect(b.backlog[3]).toBeLessThan(a.backlog[3]);
    expect(b.backlog[3]).toBeCloseTo(Math.max(0, (Math.max(0, (10 * DECAY - 2)) * DECAY - 2) * DECAY - 2), 6);
    // B clears; A is still digging out — B should report an overnight-reset hour, A a longer streak.
    expect(a.longestStreakHours).toBeGreaterThan(b.longestStreakHours);
  });

  it('attributes generated vs inherited backlog to the right shift', () => {
    // Deficit only during night-covered hours (global 0..4); zero capacity.
    const req = zeros();
    for (let h = 0; h <= 4; h++) req[h] = 5;
    const res = computeBacklog({}, req, dayNight);
    const night = res.shiftDiagnostics.find((s) => s.shiftId === 'night')!;
    const day = res.shiftDiagnostics.find((s) => s.shiftId === 'day')!;

    // All fresh shortfall lands in night hours (5 × 5 = 25 nurse-hours generated by night).
    expect(night.generatedBacklog).toBeCloseTo(25, 6);
    expect(day.generatedBacklog).toBeCloseTo(0, 6);
    // The day shift generates nothing of its own but INHERITS the decaying tail of night's hole.
    expect(day.inheritedBacklog).toBeGreaterThan(0);
  });

  it('flags a lone short hour as a much shorter streak than a compounding hole', () => {
    // One isolated short hour vs. a sustained multi-hour deficit — the streak length is the
    // signal the redesign wants (a lone hour reads differently from digging out of a hole).
    const lone = zeros();
    lone[50] = 1; // just above threshold for a single hour
    const loneRes = computeBacklog({}, lone, allDay);

    const sustained = zeros();
    for (let h = 40; h < 50; h++) sustained[h] = 5;
    const sustainedRes = computeBacklog({}, sustained, allDay);

    expect(loneRes.longestStreakHours).toBeLessThan(sustainedRes.longestStreakHours);
    expect(loneRes.peakBacklog).toBeLessThan(sustainedRes.peakBacklog);
    expect(BACKLOG_CAUGHT_UP_THRESHOLD).toBeGreaterThan(0);
  });
});
